### ISSUE TITLE
C64 multibank cartridges

### ISSUE THREAD

**Issue by BacchusFLT** [fadden/6502bench#98] opened 2021-07-29 15:51 UTC
The c64 sports a cartridge port that adds 8Kb of data at the address $8000 in memory. Many of them have also the feature that the ROM contains multiple banks and let you switch between them.

So the formats use would be 
* a special cart format with a header.
* plain binary read of the cart
* PRG with the load address as a word at the start.

I'm not saying the program doesn't support this use case, but I would like to hear the suggestions on how to go about working with them.
 
[Carts.zip](https://github.com/fadden/6502bench/files/6901812/Carts.zip)

**Comment by fadden** [comment] 2021-07-29 16:31
You can see an example of a cartridge dump with a header at https://6502disassembly.com/nes-smb/SuperMarioBros.html -- the header becomes part of the disassembly and has an address, because assemblers need to send the data *somewhere*, and SourceGen guarantees the the entire original file is reproduced.  It gets a little weirder for the graphics ROM (at the end of the disassembly), since that isn't actually addressable by the 6502... but since it isn't, the address used doesn't matter.

One of the things you'll notice in the SMB disassembly is that there are a couple of addresses near the start (VBlank1, VBlank2) that overlap with the fake addresses for the cartridge header.  SourceGen is intended to work with overlays, so address references in the current segment are prioritized over others, and it works fine.

The one place it gets weird is when control transfers directly between segments, e.g. you flip the ROM bank and suddenly you're executing elsewhere.  There's no built-in mechanism to automatically trace execution that way, so any such points would have to be explicitly marked as code entry points.

There's currently no way to teach SourceGen how to skip headers and extract the PRG load address automatically, but doing it manually doesn't take very long.

I found the format described [here](https://codebase64.org/doku.php?id=base:crt_file_format) and created a sample project (attached).  I just formatted the first couple of bank headers.  I used $1000 for the header data because it's outside the normal address range.
[sample.zip](https://github.com/fadden/6502bench/files/6902052/sample.zip)
You'll notice that +0000bf and +0020cf are both address $806f, but looking at the cross-reference table you can see that they're only referenced by other code within the same bank.

(It looks like it's using an inline print function (e.g. JSR to $8604 at +000110), so the instruction tracing will be a bit off unless you add an extension script to format the inline data.)

**Comment by BacchusFLT** [comment] 2021-07-30 16:59
Many thanks for the promt reply!

We have had the discussion on headers in the past, and I sympathize with the position that your logic means that all file content needs to go somewhere, whereas mine is that what is meta data shouldn't be mixed-up with the actual binary content. For the purpose of not walk around that minefield again, I stripped the cartridge file of all the headers and implemented the raw binary. 

I guess you can say that there are three levels here;
1) File formats with metadata headers for stuff like emulators and such. These headers are not really native to the system - rather native to the ecosystem. The CRT files you reference (as per the link to codebase64), and also commonly the SID files, are of this category.

2) Fileformats with system native metadata headers. This is where the C64 PRG file fits. The two bytes header doesn't have an address as they are the native system metadata to tell the system the address

3) In system headers, that are like "structs" in some high level programming languages. This data is indeed placed in memory at an address. The c64 cartridges binary start on $8000 and has has two vectors, followed by the string "CBM80" to tell the Kernal (system ROM) that this is an autostart unit. (This is a link describing that: https://codebase64.org/doku.php?id=base:assembling_your_own_cart_rom_image - I mean the "CBM80 autostart" part)

So we disagree that metadata headers (1 and 2  above) should have an address, but this is a separate discussion where I already surrendered, so I wanted to get back to the point ;-)

The raw binary image I work with has 7 banks - all with the "header" described in 3. So there are 7 blocks of $8000 to $9fff. Given that you have automation in traversing the code, that means that it's important that when addressing an address, it's quite picky that you mean the address in the current bank.

It seems it works perfectly fine to set the address to a block, and the address is changed from that point. So I was able to set $8000 on all the respective starting points.

I will work on that ROM a bit and see what I conclude.

**Comment by fadden** [comment] 2021-07-30 21:39
The Apple IIgs OMF format is essentially a worst-case variant of # 2 in your list: not only are there headers galore, the code and data is relocatable.  When loaded into memory by the system, instruction operands and data items that reference addresses within the program are filled in.  I didn't want to build an OMF decoder into the main part of the disassembler, so I did something similar to what you did: I re-implemented the system loader, and generated a new binary with just the bytes that are actually present in memory while the code is executing.  The trouble with doing so is that you lose valuable information, like the offset at which each segment starts, as well as meta-data like whether something is a code or data segment.  So the OMF conversion tool generates a stripped binary and a pre-populated project at the same time.  The project has .org directives at the start of each segment and comments identifying segment type, loader alignment restrictions, etc.

Something similar could be done for a CRT file, stripping the headers while generating .org directives and meta-data comments at the start of each chunk.  Unless you're doing this to a lot of files it's probably not worth the effort of generating a full project file though.  I have experimented with "SourceGen Edit Commands" in the past, which would allow you to write a tool that stripped the binary and generated a simple list of ".org" statements and comments, which could then be manually imported into a new project.

In any event, I believe the answer to the question of whether or not a binary with multiple overlapping segments can be successfully disassembled is "yes".  So far I've only done it in unit tests though.  There are related issues, like whether using Ctrl+G to go to an address does the right thing, that haven't been exercised much.  (Hint: it does not do the right thing; it actually goes to the first instance of the address in the file, rather than the one in the segment you're in. Patch to follow.)

**Comment by BacchusFLT** [comment] 2021-07-31 09:56
The emulator VICE has a cart convertion tool that allows me to take the CRT and generate a bin. It doesn't generate the skeleton project of course but the added value for this particular use case is quite small,.so I am good on the removal of metadata.

I should have experimented more before asking the question so I don't risk taking your time with topics already found in a FAQ, but I still hope this is not. 

My main point was really a question if the program properly could handle the scenario where you have the same address appear multiple times in the binary. I would assume there needs to be a way to define segments, and that all references would use the current segment if they reference addresses inside the segment. 

The logical behavior would be that a reference to an address would point to the first instance (like you Goto command does) or that it would reference all instances. I would assume it needs special attention if you would be contextually aware and reference a particular instance which is not the first.

**Comment by BacchusFLT** [comment] 2021-07-31 16:52
I have received errors on the assembly both for TASS and ACME. I will send that as a private mail as I am not sure how interested the general public is in that.

**Comment by fadden** [comment] 2021-08-01 21:50
The 64tass code generation issue is discussed here: https://sourceforge.net/p/tass64/bugs/59/

Short version: I didn't fully understand how 64tass generates binaries.  The code gen needs to operate in slightly different modes based on whether the output could be directly loaded into a 64K system.

I'll tie that specific problem to this issue for tracking purposes.

**Comment by fadden** [comment] 2021-08-02 03:11
64tass code generation should be fixed in https://github.com/fadden/6502bench/releases/tag/v1.7.5-dev3

**Closed by fadden** 2021-08-02 03:11 UTC
Labels: bug
