### ISSUE TITLE
Export source to html with images fails

### ISSUE THREAD

**Issue by grue74** [fadden/6502bench#145] opened 2023-02-14 17:49 UTC
Export dialog:
![image](https://user-images.githubusercontent.com/43750721/218817496-9328dfb9-7c4d-4ade-b65c-ef53eedcc437.png)

exported html:
![image](https://user-images.githubusercontent.com/43750721/218817846-f0378d19-e8f5-42de-ab82-1aaeb757dcc1.png)

screenshot from sourcegen:
![image](https://user-images.githubusercontent.com/43750721/218817735-eaef651e-7b48-439b-a1e0-33ea47adf859.png)

**Comment by fadden** [comment] 2023-02-14 18:10
It looks like opaque black is being used for the background, rather than transparent, so it's drawing black on black.  I tried a couple of the other visualizers and they seem to be working correctly, so this may be an issue with the C64 visualizer.

**Comment by fadden** [comment] 2023-02-14 18:52
I think the problem is that the C64 visualizer started generating a palette with two transparent colors when I was playing with borders.  The GIF encoder only supports having a single transparent palette entry, and it was choosing the wrong one.

I'm attaching an updated visualizer.  Can you replace your `RuntimeData/Commodore/VisC64.cs` with this and see if it fixes the problem?

[VisC64.cs.zip](https://github.com/fadden/6502bench/files/10735866/VisC64.cs.zip)

**Comment by grue74** [comment] 2023-02-14 19:49
It's working now; thanks a million!

**Comment by fadden** [comment] 2023-02-14 22:07
[Fixed in v1.8.5-dev1](https://github.com/fadden/6502bench/releases/tag/v1.8.5-dev1)

**Closed by fadden** 2023-02-14 22:07 UTC
Labels: bug
